"""Chapter E: apply wizard — Chapter F: tracking — Chapter G: post-acceptance steps + dossier."""
import time
from cap import Cap, ROOT

import json, sys
from pathlib import Path
KEEP = int(sys.argv[1]) if len(sys.argv) > 1 else 43
man = json.loads((ROOT/"manifest.json").read_text("utf-8"))
for e in man[KEEP:]:
    f = ROOT/"shots"/e["file"]
    if f.exists(): f.unlink()
(ROOT/"manifest.json").write_text(json.dumps(man[:KEEP], ensure_ascii=False, indent=1), "utf-8")
c = Cap(storage=str(ROOT / "state-registered.json"))
p = c.page
S = "E"

def btn(text, wait=900, exact=False):
    p.get_by_role("button", name=text, exact=exact).first.click()
    c.settle(wait)

# ───────── E. تقديم طلب الحج ─────────
# The season runs on its dates: the demo's date (its bar at the bottom) moves to the first day of the
# registration for direct acceptance, 12 August, the family's track
c.goto("/portal", wait=800)
p.evaluate("""() => { const k = 'sdhu-demo-v1'; const s = JSON.parse(localStorage.getItem(k) || '{}');
  s.clock = { ...(s.clock || {}), today: '2026-08-12', time: undefined }; localStorage.setItem(k, JSON.stringify(s)); }""")
c.goto("/portal")
c.shot("apply-cta", "من ملفي: زر «ابدأ الطلب الآن»", hl=[("a:has-text('ابدأ الطلب الآن')", "")], section=S)
c.click("a:has-text('ابدأ الطلب الآن')", wait=1500)
c.shot("apply-intro", "شاشة البداية: ما تحتاجه قبل التقديم", hl=[("button:has-text('لنبدأ')", "")], section=S)
btn("لنبدأ")
c.shot("apply-track", "اختيار نوع التسجيل: القبول المباشر أو القرعة", section=S)
btn("التسجيل على القبول المباشر")
c.shot("apply-forwhom", "لمن هذا الطلب؟", section=S)
btn("لي أنا")
c.shot("apply-residence", "أين تقيم حالياً؟ (يحدد المكتب تلقائياً)", section=S)
btn("داخل سوريا")
c.shot("apply-companions", "هل تود أن تصطحب أحداً معك؟", section=S)
btn("نعم")
c.shot("apply-method", "طريقة إضافة المرافقين", section=S)
btn("من دفتر العائلة")
c.shot("apply-booklet-number", "إدخال رقم دفتر العائلة أو تصويره", hl=[("button:has-text('صوّر دفتر العائلة')", "1"), ("div[dir='ltr'].grid", "2")], section=S)
btn("صوّر دفتر العائلة", wait=1400)
c.shot("apply-booklet-scan", "تصوير دفتر العائلة (قراءة ضوئية)", section=S)
p.wait_for_selector("text=من سيسافر معك؟", timeout=20000)
c.settle(1200)
c.shot("apply-booklet-members", "أفراد الدفتر كما وردوا من الشؤون المدنية", section=S)
p.get_by_role("button", name="فاطمة يوسف الحلبي").first.click(); c.settle(400)
p.get_by_role("button", name="عمر محمد الخطيب").first.click(); c.settle(600)
c.shot("apply-booklet-selected", "اختيار من سيسافر: الزوجة والابن", hl=[("button:has-text('التالي (')", "")], section=S)
p.locator("button:has-text('التالي (')").click(); c.settle(900)
c.shot("apply-review-1", "مراجعة أفراد الطلب", hl=[("button:has-text('الأفراد صحيحون')", "1"), ("button:has-text('إضافة شخص آخر')", "2")], section=S)
btn("الأفراد صحيحون", wait=1000)
p.wait_for_selector("text=هناك ملاحظات تحتاج إلى تعديل", timeout=20000)
c.settle(1000)
c.shot("apply-elig-fail", "فحص الأهلية: صاحب الطلب دون عمر القبول المباشر", section=S)
c.scroll_to("text=عدّل الطلب من هنا مباشرة", 140)
c.shot("apply-elig-fixes", "الحلول المقترحة لتعديل الطلب", hl=[("button:has-text('إضافة والد أو والدة')", "1"), ("button:has-text('التسجيل الأولي على القرعة بدلاً من ذلك')", "2")], section=S)
btn("إضافة والد أو والدة", wait=900)
c.scroll_top()
c.shot("apply-adder-id", "إضافة مرافق بالرقم الوطني (لوحة أرقام كبيرة)", section=S)
p.locator("button:has-text('والدته خديجة')").click(); c.settle(500)
c.shot("apply-adder-filled", "بعد إدخال الرقم الوطني", hl=[("button:has-text('ابحث في الشؤون المدنية')", "")], section=S)
btn("ابحث في الشؤون المدنية", wait=500)
c.shot("apply-adder-loading", "الاستعلام من الشؤون المدنية", section=S)
p.wait_for_selector("text=وجدنا هذا الشخص", timeout=15000); c.settle(900)
c.shot("apply-adder-confirm", "تأكيد الشخص الذي وجدناه", section=S)
btn("نعم، هذا هو")
c.shot("apply-adder-relation", "ما صلة القرابة؟", section=S)
btn("والدتي", wait=1000)
c.shot("apply-adder-verified", "الشؤون المدنية تؤكد صلة القرابة", hl=[("button:has-text('إضافة خديجة إلى الطلب')", "")], section=S)
btn("إضافة خديجة إلى الطلب", wait=1500)
c.shot("apply-applicant-moved", "أصبح الطلب باسم خديجة لأنها الأكبر سناً", section=S)
p.wait_for_selector("text=هناك ملاحظات تحتاج إلى تعديل", timeout=20000); c.settle(800)
c.scroll_to("text=عدّل الطلب من هنا مباشرة", 140)
c.shot("apply-elig-elderly", "كبيرة السن تحتاج مرافقاً مسمّى", hl=[("button:has-text('اختر مرافقاً')", "")], section=S)
btn("اختر مرافقاً", wait=900)
c.scroll_top()
c.shot("apply-elderly-pick", "اختيار مرافق كبير السن", section=S)
p.get_by_role("button", name="محمد", exact=False).first.click(); c.settle(900)
c.shot("apply-elderly-done", "تم تحديد المرافق", hl=[("button:has-text('التحقق من الأهلية')", "")], section=S)
btn("التحقق من الأهلية", wait=1000)
p.wait_for_selector("text=جميع أفراد الطلب مستوفون للشروط", timeout=25000); c.settle(1000)
c.shot("apply-elig-pass", "جميع أفراد الطلب مستوفون للشروط", section=S)
c.scroll_by(700)
c.shot("apply-elig-pass-2", "تفاصيل الفحص لكل فرد وشروط الطلب ككل", hl=[("button:has-text('متابعة')", "")], section=S)
btn("متابعة", wait=1500)
c.scroll_top()
c.shot("apply-consents", "طلبات الموافقة أُرسلت إلى أفراد الطلب", section=S)
# save & continue later
c.scroll_to("button:has-text('احفظ وتابع لاحقاً')", 400)
c.shot("apply-consents-later", "يمكنك الحفظ والعودة لاحقاً", hl=[("button:has-text('احفظ وتابع لاحقاً')", "")], section=S)
btn("احفظ وتابع لاحقاً", wait=1800)
c.shot("portal-draft", "ملفي: طلب محفوظ لم يُقدَّم بعد", hl=[("a:has-text('متابعة الطلب')", "")], section=S)
c.click("a:has-text('متابعة الطلب')", wait=1800)
c.shot("apply-resume", "العودة إلى الطلب من حيث توقفت", section=S)
# simulate approvals
for _ in range(3):
    b = p.locator("button:has-text('محاكاة: واف')").first
    if b.count() == 0: break
    b.click(); c.settle(500)
c.settle(600)
c.shot("apply-consents-all", "وافق جميع الأفراد", hl=[("button:has-text('وافق الجميع')", "")], section=S)
btn("وافق الجميع", wait=1200)
c.shot("apply-summary", "ملخص الطلب قبل الدفع", section=S)
c.scroll_by(650)
c.shot("apply-summary-2", "ماذا يحدث بعد القبول؟ والمبلغ المطلوب الآن", hl=[("button:has-text('إلى الدفع')", "")], section=S)
btn("إلى الدفع", wait=1200)
c.scroll_top()
c.shot("apply-pay-methods", "اختيار طريقة الدفع", section=S)
btn("المصرف المعتمد", wait=900)
c.scroll_by(300)
c.shot("apply-pay-bank", "الدفع في المصرف المعتمد ورفع إشعار الدفع", section=S)
c.scroll_top()
btn("شام كاش", wait=900)
c.scroll_by(300)
c.shot("apply-pay-shamcash", "الدفع عبر شام كاش", hl=[("input[placeholder='رقم العملية في شام كاش']", "")], section=S)
p.locator("button:has-text('رقم عملية تجريبي')").click(); c.settle(400)
c.shot("apply-pay-shamcash-tx", "إدخال رقم العملية ثم تأكيد الدفع", hl=[("button:has-text('تأكيد الدفع')", "")], section=S)
btn("تأكيد الدفع", wait=900)
c.shot("apply-pay-processing", "التحقق من العملية", section=S)
p.wait_for_selector("text=تقديم الطلب نهائياً", timeout=15000); c.settle(1200)
c.shot("apply-receipt", "الإيصال الرقمي لرسم التسجيل والدفعة الأولى", hl=[("button:has-text('تقديم الطلب نهائياً')", "")], section=S)
btn("تقديم الطلب نهائياً", wait=300)
t0 = time.time()
c.wait_splash()
c.settle(600)
S = "F"
c.shot("track-submitted", "استلمنا طلبك — الإيصال والمكتب", section=S)
c.goto("/portal/apply")
c.shot("apply-existing", "لديك طلب مُقدَّم بالفعل (طلب واحد لكل شخص)", section=S)
c.goto("/portal/application", wait=300)
btn("إعادة المحاكاة", wait=200)
t0 = time.time()
def at(sec):
    d = t0 + sec - time.time()
    if d > 0: p.wait_for_timeout(int(d * 1000))
at(2.6); c.shot("track-checking", "تدقيق البيانات: مطابقة الشؤون المدنية وشروط الموسم", section=S, wait=0)
at(4.6); c.shot("track-eligible", "جميع أفراد الطلب مؤهلون", section=S, wait=0)
at(6.9); c.shot("track-direct", "اعتماد القبول المباشر وفق الأكبر سناً", section=S, wait=0)
at(9.5); c.shot("track-accepted", "مبارك! تم قبول طلبك", section=S, wait=0)
c.settle(1500)
c.scroll_to("#steps", 100)
c.shot("post-steps", "الخطوات المطلوبة بعد القبول (7 خطوات)", section="G")
# The account's sidebar, with the pages a step has not opened yet locked
c.scroll_top()
c.shot("portal-sidebar", "القائمة الجانبية: صفحات حسابك، والمقفلة منها بما يفتحها", hl=[("nav[aria-label='أقسام حساب الحاج']", "")], section="D")
c.scroll_to("#steps", 100)
c.save_state(str(ROOT / "state-submitted.json"))

# ───────── G. ما بعد القبول ─────────
S = "G"
c.scroll_by(250)
c.shot("post-confirm", "الخطوة 1: أكّد قبول الحج واقرأ التعليمات", section=S)
p.locator("div.max-h-80.overflow-y-auto").evaluate("el => { el.scrollTop = el.scrollHeight; el.dispatchEvent(new Event('scroll')); }")
c.settle(800)
c.scroll_to("button:has-text('قرأت التعليمات')", 380)
c.shot("post-confirm-read", "بعد قراءة الوثيقة كاملة: وقّع بالموافقة", hl=[("button:has-text('قرأت التعليمات')", "1"), ("button:has-text('أؤكد وأوقّع إلكترونياً')", "2")], section=S)
p.locator("button:has-text('قرأت التعليمات')").click(); c.settle(400)
btn("أؤكد وأوقّع إلكترونياً", wait=2200)
c.scroll_to("#steps", 100)
c.shot("post-confirm-done", "تم تأكيد قبولك — وتقييم المرحلة", section=S)
btn("التالي:", wait=1200)

# 2. the personal photo alone
c.scroll_to("#steps", 100)
c.shot("post-docs", "الخطوة 2: الصورة الشخصية لكل فرد", section=S)
c.scroll_by(300)
btn("رفع الناقص", wait=1200)
c.shot("post-docs-uploading", "جارٍ رفع الصورة ثم مراجعتها", section=S)
c.settle(4000)
c.shot("post-docs-approved", "الصورة مقبولة — مطابقة لمواصفات التأشيرة", section=S)
def upload_rest():
    for name in ["محمد", "فاطمة", "عمر", "خديجة"]:
        p.locator(f"button:has-text('{name}')").first.click(); c.settle(500)
        b = p.locator("button:has-text('رفع الناقص')")
        if b.count() and b.first.is_enabled():
            b.first.click(); c.settle(200)
    c.settle(7000)
upload_rest()
c.scroll_to("#steps", 100)
c.shot("post-docs-done", "الصورة الشخصية مكتملة لجميع الأفراد", section=S)
btn("التالي:", wait=1500)

def go_step(title):
    """A step opened from the step bar: «التالي» goes back to the first finished step the page has not seen go by"""
    c.scroll_to("#steps", 100)
    p.locator(f"#steps li:has-text('{title}') button").first.click(); c.settle(1200)
    c.scroll_to("#steps", 100)

def open_step(title):
    """Back on «طلبي وخطواته», a step opened from the step bar"""
    c.goto("/portal/application", wait=1500)
    go_step(title)

# 3. attached to a group in the office, by a contract signed there; the groups browsed in the public directory
c.scroll_to("#steps", 100)
c.shot("post-group", "الخطوة 3: الإلحاق بمجموعة في المكتب — ثلاث مراحل", section=S)
c.goto("/verify", wait=1200)
p.locator("[role=tab]:has-text('دليل الخدمات')").first.click(); c.settle(1500)
c.scroll_to("[role=tabpanel], main article", 140)
c.shot("post-group-dir", "دليل الخدمات: بطاقات التكتلات المعتمدة بمستواها وفنادقها ومقاعد مجموعاتها", section=S)
p.locator("article:has-text('تكتل النور') a:has-text('عرض البرنامج الكامل')").first.click(); c.settle(2200)
c.shot("post-cluster-detail", "صفحة التكتل: السكن والنقل والبرامج", section=S)
c.scroll_to("text=مجموعات التكتل", 140)
c.shot("post-group-card", "بطاقة المجموعة: رئيسها ومقاعدها المتبقية — للاطلاع", hl=[("li:has-text('مجموعة اللطيف')", "")], section=S)
open_step("الإلحاق بمجموعة")
j = p.locator("main button:has-text('جرّبها الآن')")
if j.count():
    j.first.click(); c.settle(1500)
p.locator("button:has-text('محاكاة: وقّعنا العقد')").first.click(); c.settle(6000)  # the toasts go
c.scroll_to("#steps", 100)
c.shot("post-group-done", "ألحقكم المكتب بمجموعة اللطيف — سلسلة العقد", section=S)
c.goto("/portal/application/group", wait=1800)
c.shot("post-mygroup", "مجموعتي وعقدي: المجموعة وفريقها وقناتها وعقدكم", hl=[("nav[aria-label='أقسام حساب الحاج'] a[href='/portal/application/group']", "")], section=S)
open_step("الدفعة الثانية")

# 4. the second payment
c.scroll_to("#steps", 100)
# The family takes private rooms of its own: two rooms of two beds for the four of them
p.locator("button[aria-pressed]:has-text('غرف خاصة لكم')").first.click(); c.settle(1200)
p.get_by_role("button", name="إنقاص: غرفة بأربعة أسرّة").click(); c.settle(300)
for _ in range(2):
    p.get_by_role("button", name="زيادة: غرفة بسريرين").click(); c.settle(300)
c.settle(4500)  # let the toasts go
c.scroll_to("text=نوع السكن", 150)
c.shot("post-payment", "الخطوة 4: نوع السكن — غرفتان بسريرين لأفراد الطلب الأربعة", hl=[("button:has-text('غرف خاصة لكم')", "1"), ("li:has-text('غرفة بسريرين')", "2")], section=S)
c.scroll_to("button:has-text('ادفع المتبقي')", 640)
c.shot("post-payment-receipts", "إيصال مستقل لكل تكلفة", hl=[("button:has-text('ادفع المتبقي')", "")], section=S)
btn("ادفع المتبقي", wait=1000)
c.shot("post-payment-modal", "نافذة الدفع: اختر شام كاش أو المصرف", section=S)
p.locator("div[role='dialog'] button:has-text('شام كاش')").click(); c.settle(700)
p.locator("div[role='dialog'] button:has-text('رقم عملية تجريبي')").click(); c.settle(400)
p.locator("div[role='dialog'] button:has-text('تأكيد الدفع')").click(); c.settle(3200)
c.settle(3000)  # let the toasts go
c.scroll_to("#steps", 100)
c.shot("post-payment-done", "اكتمل دفع المبلغ كاملاً", section=S)
go_step("جواز السفر")

# 5. the passport, after the second payment only
c.scroll_to("#steps", 100)
c.shot("post-passport", "الخطوة 5: جواز السفر لكل فرد — بعد الدفعة الثانية", section=S)
c.scroll_by(300)
btn("رفع الناقص", wait=1200)
c.settle(4500)
c.shot("post-docs-rejected", "أُعيد جواز كبيرة السن لأن صلاحيته قصيرة", section=S)
p.locator("button:has-text('رفع الجواز المجدَّد')").click(); c.settle(6000)
upload_rest()
c.settle(4000)
c.scroll_to("#steps", 100)
c.shot("post-passport-done", "جوازات السفر مكتملة لجميع الأفراد", section=S)
go_step("الملف الطبي")

# 6. the medical file
c.scroll_to("#steps", 100)
c.shot("post-medical", "الخطوة 6: الملف الطبي — المعلومات الصحية يسجّلها المنسق", section=S)
p.locator("button:has-text('محاكاة: المنسق يسجّل الآن')").click(); c.settle(1200)
c.scroll_to("text=كرسي متحرك", 260)
c.shot("post-medical-needs", "احتياجات خديجة كما سجّلها المنسق: تُراعى في السكن والنقل دون كلفة", hl=[("text=كرسي متحرك", "")], section=S)
c.scroll_to("text=المعلومات الصحية", 120)
c.shot("post-medical-health", "المعلومات الصحية كما سجّلها المنسق — أكّدها أو اطلب تصحيحاً", hl=[("button:has-text('المعلومات صحيحة')", "1"), ("button:has-text('أطلب تصحيحاً')", "2")], section=S)
btn("المعلومات صحيحة", wait=800)
c.scroll_to("text=اللقاحات والوثائق الطبية", 120)
c.shot("post-medical-docs", "شهادات اللقاحات والوثائق الطبية لكل فرد", hl=[("button:has-text('رفع الكل')", "")], section=S)
btn("رفع الكل", wait=4500)
c.scroll_to("#steps", 100)
c.shot("post-medical-done", "الملف الطبي مكتمل", section=S)
go_step("التأشيرة والرحلة")

# 7. the visa and the trip
c.scroll_to("#steps", 100)
c.shot("post-visa", "الخطوة 7: التأشيرة والرحلة", hl=[("button:has-text('تابع حالة التأشيرة الآن')", "")], section=S)
btn("تابع حالة التأشيرة الآن", wait=3500)
c.shot("post-visa-progress", "إصدار التأشيرات لكل فرد على حدة", section=S)
c.settle(6500)
c.scroll_to("#steps", 100)
c.shot("post-visa-done", "صدرت التأشيرات — رحلتكم جاهزة", section=S)
c.save_state(str(ROOT / "state-accepted.json"))

# ───────── H. ملف الرحلة: its pages in the sidebar ─────────
S = "H"
c.settle(5000)  # the visa's toasts go
c.scroll_top()
c.shot("dossier-nav", "صفحات ملف الرحلة في القائمة الجانبية، مفتوحة كلها بعد صدور التأشيرة", hl=[("nav[aria-label='أقسام حساب الحاج']", "")], section=S)
c.goto("/portal/application/visa", wait=1800)
c.scroll_to("text=وثائق أفراد الطلب", 130)
c.shot("dossier-documents", "وثائق أفراد الطلب: الصورة والجواز والتأشيرة لكل فرد، وحال كل منها", hl=[("button[aria-label^='جواز السفر']", "")], section=S)
p.locator("button[aria-label^='جواز السفر']").first.click(); c.settle(1000)
c.shot("dossier-document-open", "جواز السفر كما رُفع: صفحة بياناته", section=S)
p.locator("[role=dialog] button:has-text('إغلاق')").last.click(); c.settle(600)
c.goto("/portal/application/trip", wait=1800)
c.scroll_to("#cards", 130)
c.shot("dossier-cards", "بطاقات الحجاج الرقمية", section=S)
c.scroll_to("#flights", 130)
c.shot("dossier-flights", "رحلة الذهاب والعودة ومقاعد الأفراد", section=S)
c.scroll_to("#mashaer", 130)
c.shot("dossier-mashaer", "المشاعر المقدسة: المخيمات والمواقع", section=S)
p.locator("button:has-text('عرفات')").first.click(); c.settle(900)
c.shot("dossier-arafat", "تفاصيل مخيم عرفات", section=S)
c.scroll_to("#itinerary", 130)
c.shot("dossier-itinerary", "برنامج الرحلة يوماً بيوم", section=S)
c.goto("/portal/application/hotels", wait=1800)
c.scroll_to("#makkah", 130)
c.shot("dossier-makkah", "فندق مكة: الغرف والوجبات والحافلة", section=S)
c.scroll_to("#madinah", 130)
c.shot("dossier-madinah", "فندق المدينة وموعد الروضة", section=S)
c.goto("/portal/application/group", wait=1800)
c.scroll_to("#group", 130)
c.shot("dossier-group", "فريق المجموعة وقناة المجموعة", section=S)
c.scroll_to("button:has-text('عرض العقد')", 420)
c.shot("dossier-contract", "عقدكم مع المجموعة: حاله وخطواته وتكلفته", hl=[("button:has-text('عرض العقد')", "")], section=S)
btn("عرض العقد", wait=1200)
c.shot("dossier-contract-open", "العقد كما وُقّع، وزر «طباعة العقد»", section=S)
p.keyboard.press("Escape"); c.settle(600)
c.goto("/portal/application/payments", wait=1800)
c.scroll_to("#payments", 130)
c.shot("dossier-payments", "التكاليف والإيصالات", section=S)
c.goto("/portal/application", wait=1800)
c.scroll_to("text=كيف تقيّم وضوح طريقتي", 200)
c.shot("dossier-rating", "تقييم وضوح القبول والقرعة", section=S)
c.close()
print("DONE run2")
