"""Chapter E: apply wizard — Chapter F: tracking — Chapter G: post-acceptance steps + dossier."""
import time
from cap import Cap, ROOT

import json, sys
from pathlib import Path
KEEP = int(sys.argv[1]) if len(sys.argv) > 1 else 42
man = json.loads((ROOT/"manifest.json").read_text("utf-8"))
for e in man[KEEP:]:
    f = ROOT/"shots"/e["file"]
    if f.exists(): f.unlink()
(ROOT/"manifest.json").write_text(json.dumps(man[:KEEP], ensure_ascii=False, indent=1), "utf-8")
c = Cap(storage=str(ROOT / "state-submitted.json"))
c.goto("/portal/application", wait=2500)
c.scroll_to("#steps", 100)
S = "G"
p = c.page
S = "E"

def btn(text, wait=900, exact=False):
    p.get_by_role("button", name=text, exact=exact).first.click()
    c.settle(wait)

# G

S = "G"
c.scroll_by(250)
c.shot("post-confirm", "الخطوة 1: أكّد قبول الحج واقرأ التعليمات", section=S)
p.locator("div.max-h-80.overflow-y-auto").evaluate("el => { el.scrollTop = el.scrollHeight; el.dispatchEvent(new Event('scroll')); }")
c.settle(800)
c.scroll_to("button:has-text('قرأت التعليمات')", 380)
c.shot("post-confirm-read", "بعد قراءة الوثيقة كاملة: وقّع بالموافقة", hl=[("button:has-text('قرأت التعليمات')", "1"), ("button:has-text('أؤكد وأوقّع إلكترونياً')", "2")], section=S)
p.locator("button:has-text('قرأت التعليمات')").click(); c.settle(400)
btn("أؤكد وأوقّع إلكترونياً", wait=2200)
c.scroll_to("#steps", 100)
c.shot("post-confirm-done", "تم تأكيد قبولك — وتقييم المرحلة", section=S)
btn("التالي:", wait=1200)
c.scroll_to("#steps", 100)
c.shot("post-docs", "الخطوة 2: الصورة الشخصية والجواز لكل فرد", section=S)
c.scroll_by(300)
btn("رفع الناقص", wait=1200)
c.shot("post-docs-uploading", "جارٍ رفع الوثائق ثم مراجعتها", section=S)
c.settle(4500)
c.shot("post-docs-rejected", "أُعيد جواز كبيرة السن لأن صلاحيته قصيرة", section=S)
p.locator("button:has-text('رفع الجواز المجدَّد')").click(); c.settle(6000)
c.shot("post-docs-approved", "الجواز الجديد مقبول", section=S)
# other members
for name in ["محمد", "فاطمة", "عمر"]:
    p.locator(f"button:has-text('{name}')").first.click(); c.settle(500)
    b = p.locator("button:has-text('رفع الناقص')")
    if b.count():
        b.first.click(); c.settle(200)
c.settle(7000)
c.scroll_to("#steps", 100)
c.shot("post-docs-done", "الصورة والجواز مكتملان لجميع الأفراد", section=S)
btn("التالي:", wait=1500)
c.scroll_to("#steps", 100)
c.shot("post-group", "الخطوة 3: مرحلة التفويج — دليل المجموعات", section=S)
c.scroll_by(500)
c.shot("post-group-dir", "بطاقات التكتلات: المستوى والفنادق والمقاعد", section=S)
p.locator("details summary:has-text('جدول المقارنة')").click(); c.settle(700)
c.scroll_to("details[open]", 120)
c.shot("post-group-compare", "جدول المقارنة بين التكتلات", section=S)
c.scroll_to("button:has-text('تكتل النور')", 140)
p.locator("button:has-text('تكتل النور')").first.click(); c.settle(1200)
c.scroll_to("text=برنامج معتمد", 140)
c.shot("post-cluster-detail", "صفحة التكتل: السكن والنقل والبرامج", section=S)
c.scroll_to("text=المجموعة 27", 140)
c.shot("post-group-card", "بطاقة المجموعة ومنسقها", hl=[("div:has(> div > div > p:text-is('المجموعة 27')) button[aria-label^='اتصال']", "1"), ("div:has(> div > div > p:text-is('المجموعة 27')) button:has-text('محاكاة')", "2")], section=S)
p.locator("div:has(> div > div > p:text-is('المجموعة 27')) button:has-text('محاكاة')").click(); c.settle(900)
c.shot("post-contract", "عقد الحاج مع المجموعة — توقيع برمز الهاتف", section=S)
c.otp("1448")
btn("أوافق وأوقّع العقد", wait=2500)
c.scroll_to("#steps", 100)
c.shot("post-group-done", "أنتم الآن في المجموعة 27 — سلسلة التوقيع", section=S)
c.scroll_to("text=نوع السكن", 330)
c.shot("post-mygroup", "مجموعتي: الفريق والأفراد ونوع السكن وإمكانية الانتقال", section=S)
c.scroll_to("#steps", 100)
btn("التالي:", wait=1500)
c.scroll_to("#steps", 100)
# The family takes private rooms of its own: two rooms of two beds for the four of them
p.locator("button[aria-pressed]:has-text('غرف خاصة لكم')").first.click(); c.settle(1200)
p.get_by_role("button", name="إنقاص: غرفة بأربعة أسرّة").click(); c.settle(300)
for _ in range(2):
    p.get_by_role("button", name="زيادة: غرفة بسريرين").click(); c.settle(300)
c.settle(4500)  # let the toasts go
c.scroll_to("text=نوع السكن", 150)
c.shot("post-payment", "الخطوة 4: نوع السكن — غرفتان بسريرين لأفراد الطلب الأربعة", hl=[("button:has-text('غرف خاصة لكم')", "1"), ("li:has-text('غرفة بسريرين')", "2")], section=S)
c.scroll_to("button:has-text('ادفع المتبقي')", 640)
c.shot("post-payment-receipts", "إيصال مستقل لكل تكلفة", hl=[("button:has-text('ادفع المتبقي')", "")], section=S)
btn("ادفع المتبقي", wait=1000)
c.shot("post-payment-modal", "نافذة الدفع: اختر شام كاش أو المصرف", section=S)
p.locator("div[role='dialog'] button:has-text('شام كاش')").click(); c.settle(700)
p.locator("div[role='dialog'] button:has-text('رقم عملية تجريبي')").click(); c.settle(400)
p.locator("div[role='dialog'] button:has-text('تأكيد الدفع')").click(); c.settle(3200)
c.scroll_to("#steps", 100)
c.shot("post-payment-done", "اكتمل دفع المبلغ كاملاً", section=S)
btn("التالي:", wait=1500)
c.scroll_to("#steps", 100)
c.shot("post-medical", "الخطوة 5: الملف الطبي — المعلومات الصحية يسجّلها المنسق", section=S)
p.locator("button:has-text('محاكاة: المنسق يسجّل الآن')").click(); c.settle(1500)
c.scroll_to("text=كرسي متحرك", 260)
c.shot("post-medical-needs", "احتياجات خديجة كما سجّلها المنسق: تُراعى في السكن والنقل دون كلفة", hl=[("text=كرسي متحرك", "")], section=S)
c.scroll_to("text=المعلومات الصحية", 120)
c.shot("post-medical-health", "المعلومات الصحية كما سجّلها المنسق — أكّدها أو اطلب تصحيحاً", hl=[("button:has-text('المعلومات صحيحة')", "1"), ("button:has-text('أطلب تصحيحاً')", "2")], section=S)
btn("المعلومات صحيحة", wait=1000)
c.scroll_to("text=اللقاحات والوثائق الطبية", 120)
c.shot("post-medical-docs", "شهادات اللقاحات والوثائق الطبية لكل فرد", hl=[("button:has-text('رفع الكل')", "")], section=S)
btn("رفع الكل", wait=4500)
c.scroll_to("#steps", 100)
c.shot("post-medical-done", "الملف الطبي مكتمل", section=S)
btn("التالي:", wait=1500)
c.scroll_to("#steps", 100)
c.shot("post-visa", "الخطوة 6: التأشيرة والرحلة", hl=[("button:has-text('تابع حالة التأشيرة الآن')", "")], section=S)
btn("تابع حالة التأشيرة الآن", wait=3500)
c.shot("post-visa-progress", "إصدار التأشيرات لكل فرد على حدة", section=S)
c.settle(6500)
c.scroll_to("#steps", 100)
c.shot("post-visa-done", "صدرت التأشيرات — رحلتكم جاهزة", section=S)
c.save_state(str(ROOT / "state-accepted.json"))

# dossier sections
S = "H"
c.scroll_to("#cards", 130)
c.shot("dossier-cards", "بطاقات الحجاج الرقمية", section=S)
c.scroll_to("#flights", 130)
c.shot("dossier-flights", "رحلة الذهاب والعودة ومقاعد الأفراد", section=S)
c.scroll_to("#makkah", 130)
c.shot("dossier-makkah", "فندق مكة: الغرف والوجبات والحافلة", section=S)
c.scroll_to("#madinah", 130)
c.shot("dossier-madinah", "فندق المدينة وموعد الروضة", section=S)
c.scroll_to("#mashaer", 130)
c.shot("dossier-mashaer", "المشاعر المقدسة: المخيمات والمواقع", section=S)
p.locator("button:has-text('عرفات')").first.click(); c.settle(900)
c.shot("dossier-arafat", "تفاصيل مخيم عرفات", section=S)
c.scroll_to("#itinerary", 130)
c.shot("dossier-itinerary", "برنامج الرحلة يوماً بيوم", section=S)
c.scroll_to("#group", 130)
c.shot("dossier-group", "فريق المجموعة وقناة المجموعة", section=S)
c.scroll_to("#payments", 130)
c.shot("dossier-payments", "التكاليف والإيصالات والعقد", section=S)
c.scroll_by(450)
c.shot("dossier-rating", "تقييم وضوح القبول والقرعة", section=S)
c.scroll_top()
c.shot("dossier-nav", "شريط الأقسام وزر «حالتي الآن»", hl=[("a[href='/portal/season']", "")], section=S)
c.close()
print("DONE run2")
