/**
 * سجل الأيقونات المتاحة في لوحة التحكم. يخزّن المحتوى اسم الأيقونة نصاً فقط،
 * ويحوّله هذا السجل إلى مكوّن عند العرض — حتى يبقى المحتوى بيانات خالصة قابلة للتصدير.
 */
import {
  AlertTriangle,
  Award,
  BadgeCheck,
  Bell,
  BookOpen,
  BookOpenText,
  BriefcaseBusiness,
  Building2,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  Camera,
  Check,
  ClipboardList,
  Clock3,
  Compass,
  Coins,
  FileCheck2,
  FileSearch,
  FileSignature,
  FileText,
  Gem,
  Globe,
  HandHeart,
  Headset,
  HeartPulse,
  Hourglass,
  IdCard,
  Info,
  Landmark,
  Languages,
  Lock,
  LucideIcon,
  Mail,
  MapPin,
  Megaphone,
  MessageSquare,
  MoonStar,
  NotebookTabs,
  Phone,
  Plane,
  Radar,
  ScanSearch,
  ScrollText,
  ShieldCheck,
  Sparkles,
  Star,
  Stethoscope,
  Target,
  Ticket,
  UserCog,
  UserRound,
  UserRoundPlus,
  UsersRound,
  Wallet,
} from "lucide-react";

export const CMS_ICONS: Record<string, LucideIcon> = {
  AlertTriangle,
  Award,
  BadgeCheck,
  Bell,
  BookOpen,
  BookOpenText,
  BriefcaseBusiness,
  Building2,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  Camera,
  Check,
  ClipboardList,
  Clock3,
  Coins,
  Compass,
  FileCheck2,
  FileSearch,
  FileSignature,
  FileText,
  Gem,
  Globe,
  HandHeart,
  Headset,
  HeartPulse,
  Hourglass,
  IdCard,
  Info,
  Landmark,
  Languages,
  Lock,
  Mail,
  MapPin,
  Megaphone,
  MessageSquare,
  MoonStar,
  NotebookTabs,
  Phone,
  Plane,
  Radar,
  ScanSearch,
  ScrollText,
  ShieldCheck,
  Sparkles,
  Star,
  Stethoscope,
  Target,
  Ticket,
  UserCog,
  UserRound,
  UserRoundPlus,
  UsersRound,
  Wallet,
};

export const CMS_ICON_NAMES = Object.keys(CMS_ICONS);

/** أسماء عربية مختصرة للأيقونات، تساعد الموظف على البحث عنها بالعربية */
export const CMS_ICON_LABELS: Record<string, string> = {
  AlertTriangle: "تحذير",
  Award: "جائزة",
  BadgeCheck: "توثيق",
  Bell: "إشعار",
  BookOpen: "كتاب",
  BookOpenText: "درس",
  BriefcaseBusiness: "عمل",
  Building2: "مبنى",
  CalendarClock: "موعد",
  CalendarDays: "تقويم",
  CalendarRange: "مدة",
  Camera: "تصوير",
  Check: "صح",
  ClipboardList: "قائمة",
  Clock3: "ساعة",
  Coins: "مال",
  Compass: "بوصلة",
  FileCheck2: "وثيقة مقبولة",
  FileSearch: "بحث في ملف",
  FileSignature: "توقيع",
  FileText: "ملف",
  Gem: "جوهرة",
  Globe: "عالم",
  HandHeart: "خدمة",
  Headset: "دعم",
  HeartPulse: "صحة",
  Hourglass: "انتظار",
  IdCard: "هوية",
  Info: "معلومة",
  Landmark: "معلم",
  Languages: "لغات",
  Lock: "قفل",
  Mail: "بريد",
  MapPin: "موقع",
  Megaphone: "إعلان",
  MessageSquare: "رسالة",
  MoonStar: "هلال",
  NotebookTabs: "دليل",
  Phone: "هاتف",
  Plane: "طائرة",
  Radar: "رصد",
  ScanSearch: "تدقيق",
  ScrollText: "سجل",
  ShieldCheck: "حماية",
  Sparkles: "تميّز",
  Star: "نجمة",
  Stethoscope: "طبابة",
  Target: "هدف",
  Ticket: "بطاقة",
  UserCog: "إعدادات مستخدم",
  UserRound: "شخص",
  UserRoundPlus: "تسجيل",
  UsersRound: "مجموعة",
  Wallet: "محفظة",
};

export function cmsIcon(name: unknown): LucideIcon | null {
  return typeof name === "string" && name in CMS_ICONS ? CMS_ICONS[name] : null;
}
